### ISSUE TITLE
Mejor manejo de clases para comunicación

### ISSUE THREAD

**Issue by rorromr** [rorromr/el5004#3]
RFInterface es una clase para el manejo de la comunicación con el módulo RF, se propone crear una estructura de clases para que se puedan implementar otros tipos de comunicación (eg Serial) que posean la misma interfaz.

**Comment by dawei22** [comment]
Obetos

**Comment by rorromr** [comment]
Si, debería haber una especie de ComManager, que el manejara las distintos tipos de comunicación y ofreciera una interfaz común independiente de lo que pasa por atras. Este obeto sería miembro del obeto GoKart, así lo veo yo

**Comment by rorromr** [comment]
RFInterface ya implementa ComInterface, solo falta el manager. Trabajar en rama fix-rf-interface.

**Comment by dawei22** [comment]
Ready
